name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: |
          export CI=false
          npm run build

      - name: Configure Git
        run: |
          git config --global user.email "ar5703233@gmail.com"
          git config --global user.name "abhaykumar30"

      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.abhay }}@github.com/${{ github.repository }}.git
          npm run deploy
